version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
      #    volumes:
      #      - ./data/db:/var/lib/postgresql/data

